INFO     root:charm_metrics.py:127 Loop device None not found
INFO     juju.model:model.py:3211 Waiting for model:
  test-t9v6wpyl/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:3211 Waiting for model:
  test-t9v6wpyl/0 [idle] active:
INFO     juju.model:model.py:3211 Waiting for model:
  test-t9v6wpyl/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:3211 Waiting for model:
  test-t9v6wpyl/0 [executing] maintenance: Reconciling runners
INFO     tests.integration.helpers.common:common.py:484 Wait for condition not met, sleeping 30
INFO     tests.integration.helpers.openstack:openstack.py:102 [TEST SETUP] Run command pkill -9 run.sh on test-t9v6wpyl-0-352f26832239
WARNING  tests.integration.helpers.openstack:openstack.py:104 dict_values([[{'version': 4, 'addr': '10.145.193.221', 'OS-EXT-IPS:type': 'fixed', 'OS-EXT-IPS-MAC:mac_addr': 'fa:16:3e:28:72:9b'}]])
WARNING  root:openstack.py:121 ssh_cmd: su - ubuntu -c 'ssh -i /home/runner-manager/.ssh/test-t9v6wpyl-0-352f26832239.key -o "StrictHostKeyChecking no" ubuntu@10.145.193.221 pkill -9 run.sh'
INFO     root:charm_metrics.py:248 Runner test-t9v6wpyl-0-352f26832239 status: online
INFO     root:charm_metrics.py:250 Runner still marked as online, waiting for it to be marked offline
INFO     juju.model:model.py:3211 Waiting for model:
  test-t9v6wpyl/0 [executing] active: 
INFO     juju.model:model.py:3211 Waiting for model:
  test-t9v6wpyl/0 [idle] active: 
INFO     root:common.py:568 File content of /var/log/github-runner-metrics.log: {"timestamp": 1733764212.7798355, "event": "reconciliation", "flavor": "test-t9v6wpyl", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 18.685848236083984}
{"timestamp": 1733764230.0935054, "event": "reconciliation", "flavor": "test-t9v6wpyl", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 16.341063976287842}
{"timestamp": 1733764370.8786938, "event": "reconciliation", "flavor": "test-t9v6wpyl", "crashed_runners": 0, "idle_runners": 1, "active_runners": 0, "expected_runners": 1, "duration": 122.32287359237671}
{"timestamp": 1733764403.9588077, "event": "reconciliation", "flavor": "test-t9v6wpyl", "crashed_runners": 0, "idle_runners": 1, "active_runners": 0, "expected_runners": 1, "duration": 32.027947664260864}
{"timestamp": 1733764340.0, "event": "runner_installed", "flavor": "test-t9v6wpyl", "duration": 78.50719451904297}
{"timestamp": 1733764430.0, "event": "runner_start", "flavor": "test-t9v6wpyl", "workflow": "Workflow Dispatch Crash Tests", "repo": "canonical/github-runner-operator", "github_event": "workflow_dispatch", "idle": 90.0, "queue_duration": 7.0}
{"timestamp": 1733764470.0, "event": "runner_stop", "flavor": "test-t9v6wpyl", "workflow": "Workflow Dispatch Crash Tests", "repo": "canonical/github-runner-operator", "github_event": "workflow_dispatch", "status": "abnormal", "status_info": {"code": 137}, "job_duration": 40.0, "job_conclusion": "cancelled"}
{"timestamp": 1733764565.4521067, "event": "reconciliation", "flavor": "test-t9v6wpyl", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 27.560924291610718}
{"timestamp": 1733764584.771392, "event": "reconciliation", "flavor": "test-t9v6wpyl", "crashed_runners": 0, "idle_runners": 0, "active_runners": 0, "expected_runners": 0, "duration": 18.233854055404663}
INFO     pytest_operator.plugin:plugin.py:929 Model status:

Model                            Controller  Cloud/Region         Version  SLA          Timestamp
test-charm-metrics-failure-2vnz  lxd         localhost/localhost  3.6.0    unsupported  17:16:44Z

App                          Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder           active      1  github-runner-image-builder  latest/edge    2  no       
test-t9v6wpyl                         active      1  github-runner                               0  yes      

Unit                            Workload  Agent  Machine  Public address  Ports     Message
github-runner-image-builder/0*  active    idle   0        10.35.65.88               
test-t9v6wpyl/0*                active    idle   1        10.35.65.94     8080/tcp  

Machine  State    Address      Inst id        Base          AZ  Message
0        started  10.35.65.88  juju-6c26d7-0  ubuntu@22.04      Running
1        started  10.35.65.94  juju-6c26d7-1  ubuntu@22.04      Running

INFO     pytest_operator.plugin:plugin.py:935 Juju error logs:

unit-test-t9v6wpyl-0: 17:04:13 CRITICAL unit.test-t9v6wpyl/0.juju-log test mode is enabled
unit-test-t9v6wpyl-0: 17:04:45 CRITICAL unit.test-t9v6wpyl/0.juju-log test mode is enabled
unit-test-t9v6wpyl-0: 17:05:29 CRITICAL unit.test-t9v6wpyl/0.juju-log image:0: test mode is enabled
unit-test-t9v6wpyl-0: 17:08:22 CRITICAL unit.test-t9v6wpyl/0.juju-log test mode is enabled
unit-test-t9v6wpyl-0: 17:09:04 ERROR unit.test-t9v6wpyl/0.juju-log pre-job-metrics.json not found for runner test-t9v6wpyl-0-252853baf6d4
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-t9v6wpyl-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-t9v6wpyl-0-252853baf6d4/pre-job-metrics.json'
unit-test-t9v6wpyl-0: 17:09:04 ERROR unit.test-t9v6wpyl/0.juju-log Pre-job metrics for runner test-t9v6wpyl-0-252853baf6d4 not found, stop extracting post-jobs metrics.
unit-test-t9v6wpyl-0: 17:09:11 CRITICAL unit.test-t9v6wpyl/0.juju-log test mode is enabled
unit-test-t9v6wpyl-0: 17:09:13 CRITICAL unit.test-t9v6wpyl/0.juju-log test mode is enabled
unit-test-t9v6wpyl-0: 17:09:52 CRITICAL unit.test-t9v6wpyl/0.juju-log test mode is enabled
unit-test-t9v6wpyl-0: 17:09:53 CRITICAL unit.test-t9v6wpyl/0.juju-log test mode is enabled
unit-test-t9v6wpyl-0: 17:10:13 CRITICAL unit.test-t9v6wpyl/0.juju-log test mode is enabled
unit-test-t9v6wpyl-0: 17:10:30 CRITICAL unit.test-t9v6wpyl/0.juju-log test mode is enabled
unit-test-t9v6wpyl-0: 17:10:47 CRITICAL unit.test-t9v6wpyl/0.juju-log test mode is enabled
unit-test-t9v6wpyl-0: 17:10:48 CRITICAL unit.test-t9v6wpyl/0.juju-log test mode is enabled
unit-test-t9v6wpyl-0: 17:12:51 CRITICAL unit.test-t9v6wpyl/0.juju-log test mode is enabled
unit-test-t9v6wpyl-0: 17:15:09 CRITICAL unit.test-t9v6wpyl/0.juju-log test mode is enabled
unit-test-t9v6wpyl-0: 17:15:36 CRITICAL unit.test-t9v6wpyl/0.juju-log test mode is enabled
unit-test-t9v6wpyl-0: 17:15:37 CRITICAL unit.test-t9v6wpyl/0.juju-log test mode is enabled
unit-test-t9v6wpyl-0: 17:16:06 CRITICAL unit.test-t9v6wpyl/0.juju-log test mode is enabled

INFO     pytest_operator.plugin:plugin.py:1017 Forgetting model main...