INFO     juju.model:model.py:3211 Waiting for model:
  test-n92whuaq/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:3211 Waiting for model:
  test-n92whuaq/0 [idle] active:
INFO     juju.model:model.py:3211 Waiting for model:
  test-n92whuaq/0 [executing] active: 
INFO     juju.model:model.py:3211 Waiting for model:
  test-n92whuaq/0 [idle] active: 
INFO     tests.integration.helpers.openstack:openstack.py:49 [TEST SETUP] Exposing port 8080 on test-n92whuaq-0-0be1f5ab21dc
WARNING  tests.integration.helpers.openstack:openstack.py:51 dict_values([[{'version': 4, 'addr': '10.145.193.132', 'OS-EXT-IPS:type': 'fixed', 'OS-EXT-IPS-MAC:mac_addr': 'fa:16:3e:4c:0f:86'}]])
INFO     tests.integration.helpers.openstack:openstack.py:104 [TEST SETUP] Run command nc -z localhost 8080 on test-n92whuaq-0-0be1f5ab21dc
WARNING  tests.integration.helpers.openstack:openstack.py:106 dict_values([[{'version': 4, 'addr': '10.145.193.132', 'OS-EXT-IPS:type': 'fixed', 'OS-EXT-IPS-MAC:mac_addr': 'fa:16:3e:4c:0f:86'}]])
WARNING  root:openstack.py:123 ssh_cmd: su - ubuntu -c 'ssh -i /home/runner-manager/.ssh/test-n92whuaq-0-0be1f5ab21dc.key -o "StrictHostKeyChecking no" ubuntu@10.145.193.132 nc -z localhost 8080'
INFO     tests.integration.helpers.openstack:openstack.py:104 [TEST SETUP] Run command curl http://localhost:8080 on test-n92whuaq-0-0be1f5ab21dc
WARNING  tests.integration.helpers.openstack:openstack.py:106 dict_values([[{'version': 4, 'addr': '10.145.193.132', 'OS-EXT-IPS:type': 'fixed', 'OS-EXT-IPS-MAC:mac_addr': 'fa:16:3e:4c:0f:86'}]])
WARNING  root:openstack.py:123 ssh_cmd: su - ubuntu -c 'ssh -i /home/runner-manager/.ssh/test-n92whuaq-0-0be1f5ab21dc.key -o "StrictHostKeyChecking no" ubuntu@10.145.193.132 curl http://localhost:8080'
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 60
INFO     juju.model:model.py:3211 Waiting for model:
  test-n92whuaq/0 [executing] active: 
INFO     pytest_operator.plugin:plugin.py:929 Model status:

Model                   Controller  Cloud/Region         Version  SLA          Timestamp
test-charm-runner-t9vc  lxd         localhost/localhost  3.6.1    unsupported  10:44:01Z

App                          Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder           active      1  github-runner-image-builder  latest/edge    2  no       
test-n92whuaq                         active      1  github-runner                               0  yes      

Unit                            Workload  Agent  Machine  Public address  Ports     Message
github-runner-image-builder/0*  active    idle   0        10.237.138.142            
test-n92whuaq/0*                active    idle   1        10.237.138.125  8080/tcp  

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.237.138.142  juju-17f9a3-0  ubuntu@22.04      Running
1        started  10.237.138.125  juju-17f9a3-1  ubuntu@22.04      Running

INFO     pytest_operator.plugin:plugin.py:935 Juju error logs:

unit-test-n92whuaq-0: 10:26:55 ERROR unit.test-n92whuaq/0.juju-log pre-job-metrics.json not found for runner test-n92whuaq-0-350aa921dc56
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-n92whuaq-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-n92whuaq-0-350aa921dc56/pre-job-metrics.json'
unit-test-n92whuaq-0: 10:26:55 ERROR unit.test-n92whuaq/0.juju-log Pre-job metrics for runner test-n92whuaq-0-350aa921dc56 not found, stop extracting post-jobs metrics.
unit-test-n92whuaq-0: 10:30:09 ERROR unit.test-n92whuaq/0.juju-log image:0: pre-job-metrics.json not found for runner test-n92whuaq-0-be29bc1aaab5
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-n92whuaq-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-n92whuaq-0-be29bc1aaab5/pre-job-metrics.json'
unit-test-n92whuaq-0: 10:30:09 ERROR unit.test-n92whuaq/0.juju-log image:0: Pre-job metrics for runner test-n92whuaq-0-be29bc1aaab5 not found, stop extracting post-jobs metrics.
unit-test-n92whuaq-0: 10:33:02 ERROR unit.test-n92whuaq/0.juju-log pre-job-metrics.json not found for runner test-n92whuaq-0-bda372168fdf
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-n92whuaq-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-n92whuaq-0-bda372168fdf/pre-job-metrics.json'
unit-test-n92whuaq-0: 10:33:02 ERROR unit.test-n92whuaq/0.juju-log Pre-job metrics for runner test-n92whuaq-0-bda372168fdf not found, stop extracting post-jobs metrics.
unit-test-n92whuaq-0: 10:36:36 ERROR unit.test-n92whuaq/0.juju-log post-job-metrics.json not found for runner test-n92whuaq-0-954753e21876
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-n92whuaq-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-n92whuaq-0-954753e21876/post-job-metrics.json'

INFO     pytest_operator.plugin:plugin.py:1017 Forgetting model main...