18:25:16 INFO IP Address to use as the fake jobmanager: 10.151.128.182
18:25:16 WARNING unexpected facade SSHServer received from the controller
18:25:16 INFO Adding model github-pr-587b7-lxd:test-jobmanager-reactive-yw5l on cloud localhost
18:25:16 WARNING unexpected facade SSHServer received from the controller
18:25:16 WARNING unexpected facade SSHSession received from the controller
18:25:16 WARNING unexpected facade SSHTunneler received from the controller
18:25:17 WARNING unexpected facade SSHServer received from the controller
18:25:18 INFO Deploying ch:amd64/jammy/mongodb-229
18:25:19 INFO Deploying ch:amd64/jammy/github-runner-image-builder-126
18:25:34 INFO Deploying local:jammy/github-runner-0
18:25:34 INFO Waiting for model:
  test-p479vl11/0 [allocating] waiting: waiting for machine
  github-runner-image-builder-p479vl11/0 [allocating] waiting: waiting for machine
18:26:05 INFO Waiting for model:
  test-p479vl11/0 [allocating] waiting: waiting for machine
  github-runner-image-builder-p479vl11/0 [allocating] waiting: waiting for machine
18:26:35 INFO Waiting for model:
  test-p479vl11/0 [executing] waiting: agent initialising
  github-runner-image-builder-p479vl11/0 [allocating] waiting: waiting for machine
18:27:05 INFO Waiting for model:
  test-p479vl11/0 [executing] maintenance: installing charm software
  github-runner-image-builder-p479vl11/0 [allocating] waiting: waiting for machine
18:27:35 INFO Waiting for model:
  test-p479vl11/0 [idle] blocked: Please provide image integration.
  github-runner-image-builder-p479vl11/0 [executing] maintenance: Setting up Builder.
18:28:05 INFO Waiting for model:
  test-p479vl11/0 [idle] blocked: Please provide image integration.
  github-runner-image-builder-p479vl11/0 [executing] maintenance: Setting up Builder.
18:28:35 INFO Waiting for model:
  test-p479vl11/0 [idle] blocked: Please provide image integration.
  github-runner-image-builder-p479vl11/0 [executing] maintenance: Setting up Builder.
18:29:06 INFO Waiting for model:
  test-p479vl11/0 [idle] blocked: Please provide image integration.
  github-runner-image-builder-p479vl11/0 [executing] maintenance: Setting up Builder.
18:29:36 INFO Waiting for model:
  test-p479vl11/0 [idle] blocked: Please provide image integration.
  github-runner-image-builder-p479vl11/0 [executing] maintenance: Setting up Builder.
18:30:07 INFO Waiting for model:
  test-p479vl11/0 [idle] blocked: Please provide image integration.
  github-runner-image-builder-p479vl11/0 [executing] maintenance: Setting up Builder.
18:30:37 INFO Waiting for model:
  test-p479vl11/0 [idle] blocked: Please provide image integration.
  github-runner-image-builder-p479vl11/0 [executing] maintenance: Setting up Builder.
18:31:08 INFO Waiting for model:
  test-p479vl11/0 [idle] waiting: Waiting for image over integration.
  github-runner-image-builder-p479vl11/0 [executing] blocked: image integration required.
18:31:38 INFO Waiting for model:
  test-p479vl11/0 [idle] waiting: Waiting for image over integration.
  github-runner-image-builder-p479vl11/0 [executing] active: Building image.
18:32:08 INFO Waiting for model:
  test-p479vl11/0 [idle] waiting: Waiting for image over integration.
  github-runner-image-builder-p479vl11/0 [executing] active: Building image.
18:32:23 INFO OpenStack servers: []
18:32:23 INFO cli: juju debug-log --model github-pr-587b7-lxd:test-jobmanager-reactive-yw5l --limit 1000
18:32:24 INFO Model status:

Model                          Controller           Cloud/Region         Version  SLA          Timestamp
test-jobmanager-reactive-yw5l  github-pr-587b7-lxd  localhost/localhost  3.6.9    unsupported  18:32:24Z

App                                   Version  Status   Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder-p479vl11           error        1  github-runner-image-builder  latest/edge  126  no       hook failed: "image-relation-changed"
mongodb                               6.0.24   active       1  mongodb                      6/edge       229  no       
test-p479vl11                                  waiting      1  github-runner                               0  no       Waiting for image over integration.

Unit                                     Workload  Agent  Machine  Public address  Ports      Message
github-runner-image-builder-p479vl11/0*  error     idle   1        10.157.62.6                hook failed: "image-relation-changed"
mongodb/0*                               active    idle   0        10.157.62.179   27017/tcp  Primary.
test-p479vl11/0*                         waiting   idle   2        10.157.62.92               Waiting for image over integration.

Machine  State    Address        Inst id        Base          AZ             Message
0        started  10.157.62.179  juju-24cabf-0  ubuntu@22.04  github-runner  Running
1        started  10.157.62.6    juju-24cabf-1  ubuntu@22.04  github-runner  Running
2        started  10.157.62.92   juju-24cabf-2  ubuntu@22.04  github-runner  Running

18:32:25 INFO Juju error logs:

machine-0: 18:26:12 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 18:26:12 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mongodb-0: 18:26:12 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 18:26:21 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 18:26:21 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-test-p479vl11-0: 18:26:21 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mongodb-0: 18:26:42 ERROR unit.mongodb/0.juju-log Unable to set params: ['vm.max_map_count']
unit-mongodb-0: 18:26:42 ERROR unit.mongodb/0.juju-log Error setting values on sysctl: Unable to set params: ['vm.max_map_count']
machine-1: 18:27:08 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 18:27:08 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-github-runner-image-builder-p479vl11-0: 18:27:08 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-test-p479vl11-0: 18:27:19 ERROR unit.test-p479vl11/0.juju-log Missing image integration.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-p479vl11-0/charm/./src/charm.py", line 118, in func_with_catch_errors
    func(self, event)
  File "/var/lib/juju/agents/unit-test-p479vl11-0/charm/./src/charm.py", line 342, in _on_config_changed
    self._check_image_ready()
  File "/var/lib/juju/agents/unit-test-p479vl11-0/charm/./src/charm.py", line 512, in _check_image_ready
    raise ImageIntegrationMissingError("No image integration found")
errors.ImageIntegrationMissingError: No image integration found
unit-test-p479vl11-0: 18:27:21 ERROR unit.test-p479vl11/0.juju-log Missing image integration.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-p479vl11-0/charm/./src/charm.py", line 118, in func_with_catch_errors
    func(self, event)
  File "/var/lib/juju/agents/unit-test-p479vl11-0/charm/./src/charm.py", line 313, in _on_start
    self._check_image_ready()
  File "/var/lib/juju/agents/unit-test-p479vl11-0/charm/./src/charm.py", line 512, in _check_image_ready
    raise ImageIntegrationMissingError("No image integration found")
errors.ImageIntegrationMissingError: No image integration found
unit-github-runner-image-builder-p479vl11-0: 18:27:47 ERROR unit.github-runner-image-builder-p479vl11/0.juju-log Pipx command failed, code: 1, out: None, err: None
unit-test-p479vl11-0: 18:30:47 ERROR unit.test-p479vl11/0.juju-log image:4: Missing image in image integration.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-p479vl11-0/charm/./src/charm.py", line 118, in func_with_catch_errors
    func(self, event)
  File "/var/lib/juju/agents/unit-test-p479vl11-0/charm/./src/charm.py", line 477, in _on_image_relation_changed
    self._check_image_ready()
  File "/var/lib/juju/agents/unit-test-p479vl11-0/charm/./src/charm.py", line 514, in _check_image_ready
    raise ImageNotFoundError("No image found in the image integration")
errors.ImageNotFoundError: No image found in the image integration
unit-github-runner-image-builder-p479vl11-0: 18:31:37 ERROR unit.github-runner-image-builder-p479vl11/0.juju-log image:4: Image build failed, code: 1, out: , err: None, stdout: 
unit-github-runner-image-builder-p479vl11-0: 18:31:45 ERROR unit.github-runner-image-builder-p479vl11/0.juju-log image:4: Image build failed, code: 1, out: , err: None, stdout: 
unit-github-runner-image-builder-p479vl11-0: 18:31:52 ERROR unit.github-runner-image-builder-p479vl11/0.juju-log image:4: Image build failed, code: 1, out: , err: None, stdout: 
unit-github-runner-image-builder-p479vl11-0: 18:32:03 ERROR unit.github-runner-image-builder-p479vl11/0.juju-log image:4: Image build failed, code: 1, out: , err: None, stdout: 
unit-github-runner-image-builder-p479vl11-0: 18:32:21 ERROR unit.github-runner-image-builder-p479vl11/0.juju-log image:4: Image build failed, code: 1, out: , err: None, stdout: 
unit-github-runner-image-builder-p479vl11-0: 18:32:21 ERROR unit.github-runner-image-builder-p479vl11/0.juju-log image:4: Uncaught exception while in charm code:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/src/builder.py", line 523, in _run
    stdout = subprocess.check_output(  # pylint: disable=unexpected-keyword-arg # nosec:B603
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/run-one', '/usr/bin/sudo', '--preserve-env', '/home/ubuntu/.local/bin/github-runner-image-builder', '--os-cloud', 'builder', 'run', 'github-runner-image-builder-p479vl11-noble-x64', '--flavor', 'shared.xsmall', '--keep-revisions', '2', '--network', 'net_stg-ps7-github-runner-test-amd64', '--prefix', 'github-runner-image-builder-p479vl11', '--upload-clouds', 'stg-ps7-github-runner-test-amd64_project_stg-ps7-github-runner-test-amd64', '--arch', 'x64', '--base-image', 'noble', '--script-url', 'https://git.launchpad.net/job-manager/plain/scripts/post-image-build.sh?h=main', '--proxy', 'egress.ps7.internal:3128']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/venv/tenacity/__init__.py", line 338, in wrapped_f
    return copy(f, *args, **kw)
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/venv/tenacity/__init__.py", line 477, in __call__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/venv/tenacity/__init__.py", line 378, in iter
    result = action(retry_state)
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/venv/tenacity/__init__.py", line 420, in exc_check
    raise retry_exc.reraise()
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/venv/tenacity/__init__.py", line 187, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/venv/tenacity/__init__.py", line 480, in __call__
    result = fn(*args, **kwargs)
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/src/builder.py", line 553, in _run
    raise BuilderRunError from exc
exceptions.BuilderRunError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/./src/charm.py", line 339, in <module>
    ops.main.main(GithubRunnerImageBuilderCharm)
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/venv/ops/__init__.py", line 363, in main
    return _legacy_main.main(
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/venv/ops/main.py", line 39, in main
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/venv/ops/_main.py", line 504, in main
    manager.run()
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/venv/ops/_main.py", line 488, in run
    self._emit()
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/venv/ops/_main.py", line 423, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/venv/ops/_main.py", line 467, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/venv/ops/framework.py", line 924, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/venv/ops/framework.py", line 1036, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/src/charm_utils.py", line 68, in wrapper
    return method(instance, event)
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/./src/charm.py", line 153, in _on_image_relation_changed
    self._run(cloud_id=cloud_id)
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/./src/charm.py", line 253, in _run
    cloud_images = builder.run(
  File "/var/lib/juju/agents/unit-github-runner-image-builder-p479vl11-0/charm/src/builder.py", line 435, in run
    build_results = pool.map(_run, build_configs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
exceptions.BuilderRunError
unit-github-runner-image-builder-p479vl11-0: 18:32:22 ERROR juju.worker.uniter.operation hook "image-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1

18:32:25 INFO Forgetting model main...