INFO     pytest_operator.plugin:plugin.py:745 Adding model lxd:test-charm-upgrade-rxdy on cloud localhost
WARNING  juju.client.connection:connection.py:893 unexpected facade AgentLifeFlag received from the controller
WARNING  juju.client.connection:connection.py:909 unknown common facade version for AgentLifeFlag,
versions known to client : [2, 3]
versions known to controller : [1]
WARNING  juju.client.connection:connection.py:893 unexpected facade SecretsDrain received from the controller
INFO     juju.model:model.py:1988 Deploying ch:amd64/github-runner-image-builder-2
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder (not enough units yet - 0/1)
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [executing] maintenance: Setting up Builder.
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [executing] maintenance: Setting up Builder.
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [executing] maintenance: Setting up Builder.
INFO     juju.model:model.py:2641 Waiting for model:
  github-runner-image-builder/0 [idle] active:
INFO     juju.model:model.py:1988 Deploying local:jammy/github-runner-0
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [allocating] waiting: waiting for machine
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] blocked: Please provide image integration.
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Update image for runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:2641 Waiting for model:
  test-akzpkcic/0 [idle] active:
INFO     pytest_operator.plugin:plugin.py:929 Model status:

Model                    Controller  Cloud/Region         Version  SLA          Timestamp
test-charm-upgrade-rxdy  lxd         localhost/localhost  3.1.10   unsupported  20:04:13Z

App                          Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder           active      1  github-runner-image-builder  latest/edge    2  no       
test-akzpkcic                         active      1  github-runner                               1  no       

Unit                            Workload  Agent  Machine  Public address  Ports  Message
github-runner-image-builder/0*  active    idle   0        10.230.19.192          
test-akzpkcic/0*                active    idle   1        10.230.19.125          

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.230.19.192  juju-e40c4c-0  ubuntu@22.04      Running
1        started  10.230.19.125  juju-e40c4c-1  ubuntu@22.04      Running

INFO     pytest_operator.plugin:plugin.py:935 Juju error logs:

unit-test-akzpkcic-0: 19:51:46 ERROR unit.test-akzpkcic/0.juju-log image:0: pre-job-metrics.json not found for runner test-akzpkcic-0-9b595e16d86c
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-akzpkcic-0-9b595e16d86c/pre-job-metrics.json'
unit-test-akzpkcic-0: 19:51:46 ERROR unit.test-akzpkcic/0.juju-log image:0: Pre-job metrics for runner test-akzpkcic-0-9b595e16d86c not found, stop extracting post-jobs metrics.
unit-test-akzpkcic-0: 19:57:01 ERROR unit.test-akzpkcic/0.juju-log image:0: Timeout creating openstack server test-akzpkcic-0-cc0b92112be3
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 227, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/openstack/cloud/_utils.py", line 224, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/openstack/cloud/_compute.py", line 1021, in create_server
    server = self.wait_for_server(
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/openstack/cloud/_compute.py", line 1142, in wait_for_server
    for count in utils.iterate_timeout(
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/openstack/utils.py", line 73, in iterate_timeout
    raise exceptions.ResourceTimeout(message)
openstack.exceptions.ResourceTimeout: Timeout waiting for the server to come up.
unit-test-akzpkcic-0: 19:57:07 ERROR unit.test-akzpkcic/0.juju-log image:0: Failed to spawn a runner.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 227, in launch_instance
    server = conn.create_server(
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/openstack/cloud/_utils.py", line 224, in func_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/openstack/cloud/_compute.py", line 1021, in create_server
    server = self.wait_for_server(
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/openstack/cloud/_compute.py", line 1142, in wait_for_server
    for count in utils.iterate_timeout(
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/openstack/utils.py", line 73, in iterate_timeout
    raise exceptions.ResourceTimeout(message)
openstack.exceptions.ResourceTimeout: Timeout waiting for the server to come up.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 204, in create_runner
    instance = self._openstack_cloud.launch_instance(
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 246, in launch_instance
    raise OpenStackError(f"Timeout creating openstack server {full_name}") from err
github_runner_manager.errors.OpenStackError: Timeout creating openstack server test-akzpkcic-0-cc0b92112be3

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 276, in _spawn_runners
    return (RunnerManager._create_runner(create_runner_args_sequence[0]),)
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/github_runner_manager/manager/runner_manager.py", line 404, in _create_runner
    return args.cloud_runner_manager.create_runner(registration_token=args.registration_token)
  File "/var/lib/juju/agents/unit-test-akzpkcic-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 212, in create_runner
    raise RunnerCreateError(f"Failed to create {instance_name} openstack runner") from err
github_runner_manager.errors.RunnerCreateError: Failed to create test-akzpkcic-0-cc0b92112be3 openstack runner
unit-test-akzpkcic-0: 20:04:04 CRITICAL unit.test-akzpkcic/0.juju-log test mode is enabled
unit-test-akzpkcic-0: 20:04:07 CRITICAL unit.test-akzpkcic/0.juju-log test mode is enabled
unit-test-akzpkcic-0: 20:04:09 ERROR juju.worker.uniter resolver loop error: executing operation "run action 2" for test-akzpkcic/0: action "juju-exec" (via unknown/invalid hook handler) failed: BSONObj size: 32284495 (0x1EC9F4F) is invalid. Size must be between 0 and 16793600(16MB) First element: update: "actions"
unit-test-akzpkcic-0: 20:04:09 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: executing operation "run action 2" for test-akzpkcic/0: action "juju-exec" (via unknown/invalid hook handler) failed: BSONObj size: 32284495 (0x1EC9F4F) is invalid. Size must be between 0 and 16793600(16MB) First element: update: "actions"

INFO     pytest_operator.plugin:plugin.py:1017 Forgetting model main...