INFO     juju.model:model.py:3211 Waiting for model:
  test-nopbq1rw/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:3211 Waiting for model:
  test-nopbq1rw/0 [idle] active:
INFO     juju.model:model.py:3211 Waiting for model:
  test-nopbq1rw/0 [executing] active: 
INFO     juju.model:model.py:3211 Waiting for model:
  test-nopbq1rw/0 [idle] active: 
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:448 Wait for condition not met, sleeping 10
INFO     juju.model:model.py:3211 Waiting for model:
  test-nopbq1rw/0 [executing] maintenance: Reconciling runners
INFO     juju.model:model.py:3211 Waiting for model:
  test-nopbq1rw/0 [idle] active: 
INFO     pytest_operator.plugin:plugin.py:929 Model status:

Model               Controller  Cloud/Region         Version  SLA          Timestamp
test-reactive-wzja  lxd         localhost/localhost  3.6.1    unsupported  18:09:08Z

App                          Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder           active      1  github-runner-image-builder  latest/edge    2  no       
mongodb                               active      1  mongodb                      6/edge       206  no       
test-nopbq1rw                         active      1  github-runner                               0  no       

Unit                            Workload  Agent  Machine  Public address  Ports      Message
github-runner-image-builder/0*  active    idle   0        10.221.249.198             
mongodb/0*                      active    idle   2        10.221.249.145  27017/tcp  Primary
test-nopbq1rw/0*                active    idle   1        10.221.249.35              

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.221.249.198  juju-0fd296-0  ubuntu@22.04      Running
1        started  10.221.249.35   juju-0fd296-1  ubuntu@22.04      Running
2        started  10.221.249.145  juju-0fd296-2  ubuntu@22.04      Running

INFO     pytest_operator.plugin:plugin.py:935 Juju error logs:

unit-test-nopbq1rw-0: 18:07:39 ERROR unit.test-nopbq1rw/0.juju-log Unable to get SSH connection for instance test-nopbq1rw-0-1fd24680cac2, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 356, in get_ssh_connection
    raise SSHError(
github_runner_manager.errors.SSHError: No connectable SSH addresses found, server: test-nopbq1rw-0-1fd24680cac2, addresses: ['10.145.193.121']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-nopbq1rw-0-1fd24680cac2
unit-test-nopbq1rw-0: 18:07:40 ERROR unit.test-nopbq1rw/0.juju-log Failed to get SSH connection while removing test-nopbq1rw-0-1fd24680cac2
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 440, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 356, in get_ssh_connection
    raise SSHError(
github_runner_manager.errors.SSHError: No connectable SSH addresses found, server: test-nopbq1rw-0-1fd24680cac2, addresses: ['10.145.193.121']
unit-test-nopbq1rw-0: 18:07:50 ERROR unit.test-nopbq1rw/0.juju-log runner-installed.timestamp not found for runner test-nopbq1rw-0-1fd24680cac2
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-nopbq1rw-0-1fd24680cac2/runner-installed.timestamp'
unit-test-nopbq1rw-0: 18:07:50 ERROR unit.test-nopbq1rw/0.juju-log installed timestamp not found for runner test-nopbq1rw-0-1fd24680cac2, will not extract any metrics.
unit-test-nopbq1rw-0: 18:07:54 ERROR unit.test-nopbq1rw/0.juju-log Health check failed due to unable to find keyfile for test-nopbq1rw-0-1fd24680cac2
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 589, in _check_state_and_flush
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-nopbq1rw-0-1fd24680cac2, key path: /home/runner-manager/.ssh/test-nopbq1rw-0-1fd24680cac2.key
unit-test-nopbq1rw-0: 18:07:57 ERROR unit.test-nopbq1rw/0.juju-log Unable to get SSH connection for instance test-nopbq1rw-0-1fd24680cac2, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-nopbq1rw-0-1fd24680cac2, key path: /home/runner-manager/.ssh/test-nopbq1rw-0-1fd24680cac2.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-nopbq1rw-0-1fd24680cac2
unit-test-nopbq1rw-0: 18:07:57 ERROR unit.test-nopbq1rw/0.juju-log Failed to get SSH connection while removing test-nopbq1rw-0-1fd24680cac2
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 440, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-nopbq1rw-0-1fd24680cac2, key path: /home/runner-manager/.ssh/test-nopbq1rw-0-1fd24680cac2.key
unit-test-nopbq1rw-0: 18:08:27 ERROR unit.test-nopbq1rw/0.juju-log Failed to get SSH connection while removing test-nopbq1rw-0-1fd24680cac2
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 440, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-nopbq1rw-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-nopbq1rw-0-1fd24680cac2, key path: /home/runner-manager/.ssh/test-nopbq1rw-0-1fd24680cac2.key

INFO     pytest_operator.plugin:plugin.py:1017 Forgetting model main...