INFO     juju.model:__init__.py:3254 Waiting for model:
  test-un6utz2z/0 [executing] active: 
INFO     juju.model:__init__.py:3254 Waiting for model:
  test-un6utz2z/0 [executing] maintenance: Reconciling runners
INFO     juju.model:__init__.py:3254 Waiting for model:
  test-un6utz2z/0 [executing] active: 
INFO     juju.model:__init__.py:3254 Waiting for model:
  test-un6utz2z/0 [executing] maintenance: Reconciling runners
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     tests.integration.helpers.common:common.py:525 Wait for condition not met, sleeping 10
INFO     juju.model:__init__.py:3254 Waiting for model:
  test-un6utz2z/0 [executing] maintenance: Reconciling runners
INFO     juju.model:__init__.py:3254 Waiting for model:
  test-un6utz2z/0 [idle] active: 
INFO     pytest_operator.plugin:plugin.py:929 Model status:

Model               Controller  Cloud/Region         Version  SLA          Timestamp
test-reactive-scti  lxd         localhost/localhost  3.6.1    unsupported  07:19:02Z

App                          Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder           active      1  github-runner-image-builder  latest/edge    2  no       
mongodb                               active      1  mongodb                      6/edge       206  no       
test-un6utz2z                         active      1  github-runner                               0  no       

Unit                            Workload  Agent  Machine  Public address  Ports      Message
github-runner-image-builder/0*  active    idle   0        10.55.139.170              
mongodb/0*                      active    idle   2        10.55.139.33    27017/tcp  Primary
test-un6utz2z/0*                active    idle   1        10.55.139.69               

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.55.139.170  juju-7b9703-0  ubuntu@22.04      Running
1        started  10.55.139.69   juju-7b9703-1  ubuntu@22.04      Running
2        started  10.55.139.33   juju-7b9703-2  ubuntu@22.04      Running

INFO     pytest_operator.plugin:plugin.py:935 Juju error logs:

unit-test-un6utz2z-0: 07:06:24 CRITICAL unit.test-un6utz2z/0.juju-log test mode is enabled
unit-test-un6utz2z-0: 07:07:35 CRITICAL unit.test-un6utz2z/0.juju-log test mode is enabled
unit-test-un6utz2z-0: 07:07:37 CRITICAL unit.test-un6utz2z/0.juju-log test mode is enabled
unit-test-un6utz2z-0: 07:08:14 CRITICAL unit.test-un6utz2z/0.juju-log test mode is enabled
unit-test-un6utz2z-0: 07:09:07 CRITICAL unit.test-un6utz2z/0.juju-log test mode is enabled
unit-test-un6utz2z-0: 07:09:08 CRITICAL unit.test-un6utz2z/0.juju-log test mode is enabled
unit-test-un6utz2z-0: 07:09:42 CRITICAL unit.test-un6utz2z/0.juju-log test mode is enabled
unit-test-un6utz2z-0: 07:10:18 CRITICAL unit.test-un6utz2z/0.juju-log test mode is enabled
unit-test-un6utz2z-0: 07:10:36 CRITICAL unit.test-un6utz2z/0.juju-log test mode is enabled
unit-test-un6utz2z-0: 07:10:37 CRITICAL unit.test-un6utz2z/0.juju-log test mode is enabled
unit-test-un6utz2z-0: 07:11:13 CRITICAL unit.test-un6utz2z/0.juju-log test mode is enabled
unit-test-un6utz2z-0: 07:14:44 CRITICAL unit.test-un6utz2z/0.juju-log test mode is enabled
unit-test-un6utz2z-0: 07:17:22 CRITICAL unit.test-un6utz2z/0.juju-log test mode is enabled
unit-test-un6utz2z-0: 07:17:23 CRITICAL unit.test-un6utz2z/0.juju-log test mode is enabled
unit-test-un6utz2z-0: 07:17:40 ERROR unit.test-un6utz2z/0.juju-log SSH connection failure with test-un6utz2z-0-97bddac35d89 during flushing
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-un6utz2z-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 590, in _check_state_and_flush
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-un6utz2z-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-un6utz2z-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 328, in get_ssh_connection
    raise SSHError(f"No addresses found for OpenStack server {instance.server_name}")
github_runner_manager.errors.SSHError: No addresses found for OpenStack server test-un6utz2z-0-97bddac35d89
unit-test-un6utz2z-0: 07:17:45 ERROR unit.test-un6utz2z/0.juju-log SSH connection failure with test-un6utz2z-0-97bddac35d89 during flushing
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-un6utz2z-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 590, in _check_state_and_flush
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-un6utz2z-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-un6utz2z-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 328, in get_ssh_connection
    raise SSHError(f"No addresses found for OpenStack server {instance.server_name}")
github_runner_manager.errors.SSHError: No addresses found for OpenStack server test-un6utz2z-0-97bddac35d89
unit-test-un6utz2z-0: 07:17:55 ERROR unit.test-un6utz2z/0.juju-log SSH connection failure with test-un6utz2z-0-97bddac35d89 during flushing
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-un6utz2z-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 590, in _check_state_and_flush
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-un6utz2z-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-un6utz2z-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 328, in get_ssh_connection
    raise SSHError(f"No addresses found for OpenStack server {instance.server_name}")
github_runner_manager.errors.SSHError: No addresses found for OpenStack server test-un6utz2z-0-97bddac35d89
unit-test-un6utz2z-0: 07:17:55 ERROR unit.test-un6utz2z/0.juju-log Retry limit of 3 exceed: No addresses found for OpenStack server test-un6utz2z-0-97bddac35d89
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-un6utz2z-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-un6utz2z-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 590, in _check_state_and_flush
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-un6utz2z-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-un6utz2z-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 328, in get_ssh_connection
    raise SSHError(f"No addresses found for OpenStack server {instance.server_name}")
github_runner_manager.errors.SSHError: No addresses found for OpenStack server test-un6utz2z-0-97bddac35d89
unit-test-un6utz2z-0: 07:18:03 ERROR unit.test-un6utz2z/0.juju-log runner-installed.timestamp not found for runner test-un6utz2z-0-334e1edb1210
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-un6utz2z-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-un6utz2z-0-334e1edb1210/runner-installed.timestamp'
unit-test-un6utz2z-0: 07:18:03 ERROR unit.test-un6utz2z/0.juju-log installed timestamp not found for runner test-un6utz2z-0-334e1edb1210, will not extract any metrics.
unit-test-un6utz2z-0: 07:18:20 CRITICAL unit.test-un6utz2z/0.juju-log test mode is enabled

INFO     pytest_operator.plugin:plugin.py:1017 Forgetting model main...