12:05:40 INFO Adding model lxd:test-debug-ssh-7ob6 on cloud localhost
12:05:40 WARNING unexpected facade AgentLifeFlag received from the controller
12:05:40 WARNING unknown common facade version for AgentLifeFlag,
versions known to client : [2, 3]
versions known to controller : [1]
12:05:40 WARNING unexpected facade SecretsDrain received from the controller
12:05:42 INFO Deploying ch:amd64/github-runner-image-builder-2
12:05:42 INFO Waiting for model:
  github-runner-image-builder (not enough units yet - 0/1)
12:06:12 INFO Waiting for model:
  github-runner-image-builder/0 [allocating] waiting: waiting for machine
12:06:42 INFO Waiting for model:
  github-runner-image-builder/0 [allocating] waiting: waiting for machine
12:07:13 INFO Waiting for model:
  github-runner-image-builder/0 [allocating] waiting: waiting for machine
12:07:43 INFO Waiting for model:
  github-runner-image-builder/0 [allocating] waiting: waiting for machine
12:08:13 INFO Waiting for model:
  github-runner-image-builder/0 [executing] maintenance: Setting up Builder.
12:08:43 INFO Waiting for model:
  github-runner-image-builder/0 [executing] maintenance: Setting up Builder.
12:09:13 INFO Waiting for model:
  github-runner-image-builder/0 [executing] maintenance: Setting up Builder.
12:09:43 INFO Waiting for model:
  github-runner-image-builder/0 [idle] active: 
12:10:10 INFO Deploying local:jammy/github-runner-0
12:10:10 INFO Waiting for model:
  test-fv0og5fn/0 [allocating] waiting: waiting for machine
12:10:40 INFO Waiting for model:
  test-fv0og5fn/0 [allocating] waiting: waiting for machine
12:11:10 INFO Waiting for model:
  test-fv0og5fn/0 [executing] blocked: Please provide image integration.
12:11:40 INFO Waiting for model:
  test-fv0og5fn/0 [executing] active: 
12:11:56 INFO GitHub token rate limit: Rate(reset=2024-12-20 12:43:02+00:00, remaining=4936, limit=5000)
12:12:00 INFO Deploying ch:amd64/jammy/tmate-ssh-server-6
12:12:00 WARNING relate is deprecated and will be removed. Use integrate instead.
12:12:00 INFO Waiting for model:
  tmate-ssh-server/0 [allocating] waiting: waiting for machine
12:12:30 INFO Waiting for model:
  tmate-ssh-server/0 [allocating] waiting: waiting for machine
12:13:00 INFO Waiting for model:
  tmate-ssh-server/0 [idle] active:
12:13:13 INFO Waiting for model:
  github-runner-image-builder/0 [idle] active: 
  test-fv0og5fn/0 [executing] maintenance: Reconciling runners
  tmate-ssh-server/0 [idle] active: 
12:13:43 INFO Waiting for model:
  test-fv0og5fn/0 [executing] maintenance: Reconciling runners
12:14:14 INFO Waiting for model:
  test-fv0og5fn/0 [executing] maintenance: Reconciling runners
12:14:44 INFO Waiting for model:
  test-fv0og5fn/0 [executing] active: 
12:15:14 INFO Waiting for model:
  test-fv0og5fn/0 [idle] active:
12:15:22 INFO Model status:

Model                Controller  Cloud/Region         Version  SLA          Timestamp
test-debug-ssh-7ob6  lxd         localhost/localhost  3.1.10   unsupported  12:15:22Z

App                          Version  Status  Scale  Charm                        Channel      Rev  Exposed  Message
github-runner-image-builder           active      1  github-runner-image-builder  latest/edge    2  no       
test-fv0og5fn                         active      1  github-runner                               0  no       
tmate-ssh-server                      active      1  tmate-ssh-server             edge           6  no       

Unit                            Workload  Agent  Machine  Public address  Ports      Message
github-runner-image-builder/0*  active    idle   0        10.175.159.54              
test-fv0og5fn/0*                active    idle   1        10.175.159.238             
tmate-ssh-server/0*             active    idle   2        10.175.159.254  10022/tcp  

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.175.159.54   juju-d72f67-0  ubuntu@22.04      Running
1        started  10.175.159.238  juju-d72f67-1  ubuntu@22.04      Running
2        started  10.175.159.254  juju-d72f67-2  ubuntu@22.04      Running

12:15:22 INFO Juju error logs:

machine-0: 12:07:51 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 12:07:51 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 12:07:51 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-github-runner-image-builder-0: 12:07:51 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 12:10:48 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-1: 12:10:48 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 12:10:48 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-test-fv0og5fn-0: 12:10:48 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 12:12:38 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 12:12:38 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 12:12:38 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-tmate-ssh-server-0: 12:12:38 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-test-fv0og5fn-0: 12:14:49 ERROR unit.test-fv0og5fn/0.juju-log debug-ssh:1: pre-job-metrics.json not found for runner test-fv0og5fn-0-422e6e9e3c5e
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/metrics/runner.py", line 557, in _extract_file_from_storage
    file_content = metrics_storage.path.joinpath(filename).read_text(encoding="utf-8")
  File "/usr/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner-manager/runner-fs/test-fv0og5fn-0-422e6e9e3c5e/pre-job-metrics.json'
unit-test-fv0og5fn-0: 12:14:49 ERROR unit.test-fv0og5fn/0.juju-log debug-ssh:1: Pre-job metrics for runner test-fv0og5fn-0-422e6e9e3c5e not found, stop extracting post-jobs metrics.
unit-test-fv0og5fn-0: 12:14:53 ERROR unit.test-fv0og5fn/0.juju-log debug-ssh:1: Unable to get SSH connection for instance test-fv0og5fn-0-422e6e9e3c5e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-fv0og5fn-0-422e6e9e3c5e, key path: /home/runner-manager/.ssh/test-fv0og5fn-0-422e6e9e3c5e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-fv0og5fn-0-422e6e9e3c5e
unit-test-fv0og5fn-0: 12:14:53 ERROR unit.test-fv0og5fn/0.juju-log debug-ssh:1: Failed to get SSH connection while removing test-fv0og5fn-0-422e6e9e3c5e
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/openstack_runner_manager.py", line 440, in _delete_runner
    ssh_conn = self._openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-fv0og5fn-0-422e6e9e3c5e, key path: /home/runner-manager/.ssh/test-fv0og5fn-0-422e6e9e3c5e.key
unit-test-fv0og5fn-0: 12:15:01 ERROR unit.test-fv0og5fn/0.juju-log debug-ssh:1: Unable to get SSH connection for instance test-fv0og5fn-0-422e6e9e3c5e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-fv0og5fn-0-422e6e9e3c5e, key path: /home/runner-manager/.ssh/test-fv0og5fn-0-422e6e9e3c5e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-fv0og5fn-0-422e6e9e3c5e
unit-test-fv0og5fn-0: 12:15:04 ERROR unit.test-fv0og5fn/0.juju-log debug-ssh:1: Unable to get SSH connection for instance test-fv0og5fn-0-422e6e9e3c5e, marking as unhealthy.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 130, in _get_ssh_connection
    ssh_conn = openstack_cloud.get_ssh_connection(instance)
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 138, in exception_handling_wrapper
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/openstack_cloud.py", line 324, in get_ssh_connection
    raise KeyfileError(
github_runner_manager.errors.KeyfileError: Missing keyfile for server: test-fv0og5fn-0-422e6e9e3c5e, key path: /home/runner-manager/.ssh/test-fv0og5fn-0-422e6e9e3c5e.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 49, in check_runner
    ssh_conn = _get_ssh_connection(openstack_cloud=openstack_cloud, instance=instance)
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/utilities.py", line 77, in fn_with_retry
    return func(*args, **kwargs)
  File "/var/lib/juju/agents/unit-test-fv0og5fn-0/charm/venv/github_runner_manager/openstack_cloud/health_checks.py", line 133, in _get_ssh_connection
    raise _SSHError(f"Unable to get SSH connection to {instance.server_name}") from exc
github_runner_manager.openstack_cloud.health_checks._SSHError: Unable to get SSH connection to test-fv0og5fn-0-422e6e9e3c5e

12:15:23 INFO Forgetting model main...